- id: 0
  key: renminbi
  code: cny
  symbol: "¥"
  coin: false
  precision: 2
  assets:
    accounts:
      -
        bank: '招商银行'
        address: '6225 0885 6022 3501'
        password: '111111'
        tel: '95555'
- id: 2
  key: satoshi
  code: btc
  symbol: "฿"
  coin: true
  family: BTC
  quick_withdraw_max: 0
  rpc: http://danclickomy:123456@127.0.0.1:18332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 1HjfnJpQmANtuW7yr1ggeDfyfe1kDK7rm3
- id: 3
  key: ether
  code: eth
  symbol: "฿"
  coin: true
  main_address: 6af067820fdce2d718648203530c0f02856012d9
  family: ETH
  precision: 4
  quick_withdraw_max: 0
  rpc: http://207.148.24.78:80
  rpcallowip: 207.246.121.153
  blockchain: https://etherscan.io/tx/#{txid}
  address_url: https://etherscan.io/address/#{address}
  assets:
    accounts:
      -
        address: 6af067820fdce2d718648203530c0f02856012d9

- id: 4
  key: sikret
  code: skrt
  symbol: "S"
  coin: true
  family: BTC
  quick_withdraw_max: 0
  rpc: http://danclickomy:123456@127.0.0.1:10038
  rpcallowip: 127.0.0.1
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: SQXAYxFSwVRzJwVnNihhBVXKh5AR2njhwV
